export enum BoardType {
  PROJECT = "PROJECT",
  PROJECT_INTERVIEW = "PROJECT_INTERVIEW",
}

export enum NodeType {
  STICKY_NOTE = "STICKY_NOTE",
  PROJECT_JOB = "PROJECT_JOB",
  PROJECT_INTERVIEW_JOB = "PROJECT_INTERVIEW_JOB",
  DISCUSSION = "DISCUSSION",
}
